### ISSUE TITLE
Tiny question on syntax

### ISSUE THREAD

**Issue by iburunat** [tlikonen/suomalainen-kalenteri#2]
Thanks for this package!

I have just a question regarding the syntax:

https://github.com/tlikonen/suomalainen-kalenteri/blob/56927306d8046f2ba38b8cadabde47c5b6851262/suomalainen-kalenteri.el#L95

What is the meaning of `31`? scratching my head around it ;) Thanks in advance.

**Comment by tlikonen** [comment]
Thanks. The holiday "Pyhäinpäivä" is first (1) Saturday (6) after October (10) 31st. With those numbers I referred to the arguments of this `holiday-float` call.

**Comment by iburunat** [comment]
That's a tricky location for a holiday indeed! Thanks for the clarification. Was just wondering if it could be expressed in a different way, but couldn't find any.
